INDIGO_WELCOME_MESSAGE: "The place for all your online learning"
INDIGO_PRIMARY_COLOR: "#e94154"

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"
  - title: "Donate"
    url: "https://www.givengain.com/c/girlcode/"
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "Terms of service & Honor code"
      url: "/tos"
    - title: "Privacy Policy"
      url: "/privacy"
    
