INDIGO_WELCOME_MESSAGE: "The place for all your online learning with Girlcode"
INDIGO_PRIMARY_COLOR: "#e94154"

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"
  - title: "Donate"
    url: "https://www.givengain.com/c/girlcode/"
INDIGO_FOOTER_LEGAL_LINKS:
  - title: "Terms of service & Honor code"
    url: "/tos"
  - title: "Privacy Policy"
    url: "/privacy"
INDIGO_FOOTER_SOCIAL_LINKS:
  - title: "Facebook"
    url: "https://www.facebook.com/GirlCodeZA/"
    icon-class: "facebook"
    action: "Share on Facebook"
  - title: "Twitter"
    url: "https://twitter.com/GirlCode_za"
    icon-class: "twitter"
    action: "Share on Twitter"
  - title: "Youtube"
    url: "https://www.youtube.com/channel/UC1s8oUejqyRONE-gTo9YGag"
    icon-class: "youtube"
    action: "Share on Youtube"
  - title: "Instagram"
    url: "https://www.instagram.com/girlcode_za/"
    icon-class: "instagram"
    action: "Share on Instagram"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/company/girlcodeza"
    icon-class: "linkedin"
    action: "Share on LinkedIn"